### PR TITLE
Update to version 2.29

### PR DESCRIPTION
**Pull request by jendrikseipp**

### CODE REVIEW

**Comment by jendrikseipp** [comment]
bot, build

**Comment by jendrikseipp** [comment]
bot, build

**Comment by jendrikseipp** [comment]
The builds keep failing due to the following error (which seems unrelated to the changes in this PR):

```
fusermount3: failed to access mountpoint /run/user/996/doc: Permission denied
error: fuse init failed: Can't mount path /run/user/996/doc
``` 

@scx, do you have an idea what's going wrong here?

**Comment by jendrikseipp** [comment]
bot, build

**Comment by jendrikseipp** [comment]
bot, build

**Comment by takluyver** [comment]
I think the fusermount3 error is a red herring - I just checked a successful build of another project and saw the same message there. I think the real error might be this line:

```
Error: ERROR: appstream-compose failed: Child process killed by signal 8
```

Signal 8 is SIGFPE, which from what I can find usually means a divide-by-zero error. I don't really know what could cause that, but I might try reverting all the changes in your `appdata.xml` file, to see if you've uncovered some glitch in parsing that. :confused:

**Comment by jendrikseipp** [comment]
Thanks a lot @takluyver! There must have been something wrong with parsing the appstream file indeed. When I changed the lines one by one in another PR (#20), the parsing went fine though. So we're not much wiser, but at least the builds succeed now :-)

**Comment by takluyver** [comment]
Bizarre. Glad you got it fixed.

**Pull request closed without merging**
