### PR TITLE
update runtime to 40

### PR DESCRIPTION
**Pull request by dgcampea**

### CODE REVIEW

**Comment by jendrikseipp** [comment]
Thanks for updating the runtime version @dgcampea ! When I try to test the flatpak with the command above, I get `Error: Can't load uri https://dl.flathub.org/build-repo/43075/app.rednotebook.RedNotebook.flatpakref: Server returned status 404: Not Found`. Did you check whether the resulting flatpak works?

**Comment by dgcampea** [comment]
> Thanks for updating the runtime version @dgcampea ! When I try to test the flatpak with the command above, I get `Error: Can't load uri https://dl.flathub.org/build-repo/43075/app.rednotebook.RedNotebook.flatpakref: Server returned status 404: Not Found`. Did you check whether the resulting flatpak works?

I think I checked it but not sure.

**Comment by dgcampea** [comment]
!bot build

**Comment by dgcampea** [comment]
bot, build app.rednotebook.RedNotebook

**Comment by jendrikseipp** [comment]
Thanks! LGTM.

**Pull request merged**
